INSERT INTO MentalHealthKeywords (Keyword, Category, Weight, SeverityLevel, IsActive, CreatedAt, UpdatedAt)
VALUES
-- Depression (50 từ khóa)
(N'cảm thấy buồn', 'depression', 5, 'MILD', 1, GETDATE(), NULL),
(N'mất ngủ liên tục', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'không muốn sống', 'depression', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'cô đơn thường xuyên', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi kéo dài', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'chán nản mọi thứ', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'khóc không lý do', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'tự ti bản thân', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'vô dụng hoàn toàn', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'mất hứng thú', 'depression', 5, 'MILD', 1, GETDATE(), NULL),
(N'buồn bã kéo dài', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'không còn năng lượng', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác trống rỗng', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tự trách mình', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'mất tập trung', 'depression', 5, 'MILD', 1, GETDATE(), NULL),
(N'chán ăn thường xuyên', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'ngủ quá nhiều', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'thất vọng bản thân', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác tuyệt vọng', 'depression', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'tâm trạng uể oải', 'depression', 5, 'MILD', 1, GETDATE(), NULL),
(N'không còn hy vọng', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'buồn không giải thích', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mất niềm tin', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm thấy vô nghĩa', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'không muốn giao tiếp', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác nặng nề', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'không còn động lực', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'tự cô lập', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác tội lỗi', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'khó chịu liên tục', 'depression', 5, 'MILD', 1, GETDATE(), NULL),
(N'mất kiểm soát', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'không còn cảm xúc', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'cảm giác thất bại', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'buồn bã sâu sắc', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tâm trạng chán nản', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi tinh thần', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác bất lực', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'không muốn thức dậy', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác cô độc', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'tâm trạng tiêu cực', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'mất ngủ kéo dài', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'không còn mục đích', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'cảm giác đau khổ', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tự ti quá mức', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'chán ghét bản thân', 'depression', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'cảm giác trầm trọng', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'không còn đam mê', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'tâm trạng u ám', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác hối tiếc', 'depression', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi tâm lý', 'depression', 7, 'MODERATE', 1, GETDATE(), NULL),

-- Anxiety (50 từ khóa)
(N'lo lắng thường xuyên', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'tim đập nhanh', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'khó thở đột ngột', 'anxiety', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'sợ hãi vô lý', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'bồn chồn liên tục', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'run rẩy tay chân', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'đổ mồ hôi', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng thần kinh', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ mất kiểm soát', 'anxiety', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'khó tập trung', 'anxiety', 5, 'MILD', 1, GETDATE(), NULL),
(N'lo âu kéo dài', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác bất an', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'nghĩ ngợi quá mức', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ hãi xã hội', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'khó chịu trong người', 'anxiety', 5, 'MILD', 1, GETDATE(), NULL),
(N'cảm giác hồi hộp', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ thất bại', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'tâm trạng lo lắng', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác nguy hiểm', 'anxiety', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'khó thư giãn', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng kéo dài', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ đám đông', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'tim đập mạnh', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác hoảng loạn', 'anxiety', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'lo sợ không rõ', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'tâm trạng bất ổn', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ bị đánh giá', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'khó kiểm soát lo lắng', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác ngột ngạt', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng quá mức', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ hãi kéo dài', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng tâm lý', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'khó chịu tinh thần', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ bị từ chối', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác áp lực', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng không ngừng', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'run sợ vô cớ', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác sợ hãi', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'khó chịu tâm lý', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'tâm trạng hồi hộp', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ bị bỏ rơi', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng liên tục', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng xã hội', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ hãi không rõ', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'cảm giác căng thẳng', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'khó kiểm soát sợ', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng dai dẳng', 'anxiety', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ bị hiểu lầm', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'tâm trạng bồn chồn', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'sợ mất danh dự', 'anxiety', 6, 'MODERATE', 1, GETDATE(), NULL),

-- Suicide (50 từ khóa)
(N'muốn tự tử', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'kết thúc cuộc sống', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'không muốn sống', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'tự làm hại', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn chết đi', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'chấm dứt tất cả', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'tự sát là giải pháp', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn lý do', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn từ bỏ', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'kết thúc bản thân', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'không chịu nổi', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn biến mất', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'tự hủy hoại', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn lối thoát', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn rời bỏ', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tự làm đau', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'chán sống mãi mãi', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn hy vọng', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn buông xuôi', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tự tử là lựa chọn', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'không muốn tồn tại', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn chết ngay', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'kết thúc đau khổ', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'tự hại bản thân', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn giá trị', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn chấm dứt', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'tự tử ngay bây giờ', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn ý nghĩa', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn rời đi', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tự làm tổn thương', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn sức sống', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn bỏ cuộc', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tự hủy diệt', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'kết thúc mọi thứ', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn chết lặng lẽ', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn tương lai', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'tự tử là lối thoát', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn ra đi', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'tự làm khổ mình', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn động lực', 'suicide', 8, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn kết thúc nhanh', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'tự hủy hoại mình', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn mục đích', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn rời bỏ tất cả', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'tự tử ngay lập tức', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn niềm tin', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn chấm dứt đau', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),
(N'tự làm đau mình', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'không còn ý chí', 'suicide', 9, 'SEVERE', 1, GETDATE(), NULL),
(N'muốn chết mãi mãi', 'suicide', 10, 'SEVERE', 1, GETDATE(), NULL),

-- Stress (50 từ khóa)
(N'áp lực công việc', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng quá mức', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi tinh thần', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng công việc', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực gia đình', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng liên tục', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi kéo dài', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'khó chịu tâm lý', 'stress', 5, 'MILD', 1, GETDATE(), NULL),
(N'áp lực tài chính', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng thần kinh', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi thể chất', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng tương lai', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực thời gian', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng xã hội', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi tâm lý', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực học tập', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng kéo dài', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi liên tục', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng không ngừng', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực cuộc sống', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng tâm lý', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi quá độ', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng tài chính', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực xã hội', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng công việc', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi thần kinh', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng gia đình', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực thi cử', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng tinh thần', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi áp lực', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng sức khỏe', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực trách nhiệm', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng dai dẳng', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi công việc', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng không rõ', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực kỳ vọng', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng thường xuyên', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi xã hội', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng mối quan hệ', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực hoàn hảo', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng tài chính', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi trách nhiệm', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng tương lai', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực công việc', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng áp lực', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi kéo dài', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'lo lắng không ngừng', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'áp lực xã hội', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL),
(N'căng thẳng tâm lý', 'stress', 7, 'MODERATE', 1, GETDATE(), NULL),
(N'mệt mỏi tinh thần', 'stress', 6, 'MODERATE', 1, GETDATE(), NULL);